/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simulazione;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author piter
 */
public class FrameParametri extends javax.swing.JFrame {

    /**
     * Creates new form FrameParametri
     */
    public FrameParametri() {
        initComponents();
        setTitle("Parametri");
        //setLocation(200,200);
        
        jLabel8.setEnabled(false);
        jTextNumeroProve.setEditable(false);
    }

    
    private void verifica(int numOperatori,int numCasseFaiDaTe,double paramArrivi,
            double paramOperatore,double paramFaiDaTe,double tempoSimulazione, int numProveRipetute) throws LimiteCasse,LimiteValori{
        if(numOperatori>23||numCasseFaiDaTe>11){
            throw new LimiteCasse();
        }
        
        if(paramArrivi<0||paramOperatore<0||paramFaiDaTe<0||tempoSimulazione<0||numProveRipetute<0){
            throw new LimiteValori();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextInterarrivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextOperatore = new javax.swing.JTextField();
        jTextNumOperatore = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFaiDaTe = new javax.swing.JTextField();
        jTextNumFaiDaTe = new javax.swing.JTextField();
        jTextTempoSimulazione = new javax.swing.JTextField();
        jTextNumeroProve = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonAvvio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextInterarrivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextInterarrivo.setText("18");
        jTextInterarrivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInterarrivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tempo Di Interarrivo (sec)");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Casse Operatore"));
        jPanel1.setToolTipText("");

        jLabel3.setText("Tempo Di Servizio (sec)");

        jLabel4.setText("Numero Casse");

        jTextOperatore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextOperatore.setText("183");
        jTextOperatore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOperatoreActionPerformed(evt);
            }
        });

        jTextNumOperatore.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextNumOperatore.setText("9");
        jTextNumOperatore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumOperatoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNumOperatore, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextOperatore, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextOperatore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumOperatore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/centro-commerciale-collestrada.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel7.setText("Durata Simulazione (sec)");

        jCheckBox1.setText("Prove Ripetute");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Casse Fai Da Te"));
        jPanel2.setToolTipText("");

        jLabel5.setText("Tempo Di Servizio (sec)");

        jLabel6.setText("Numero Casse");

        jTextFaiDaTe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFaiDaTe.setText("205");
        jTextFaiDaTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFaiDaTeActionPerformed(evt);
            }
        });

        jTextNumFaiDaTe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextNumFaiDaTe.setText("6");
        jTextNumFaiDaTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumFaiDaTeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNumFaiDaTe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jTextFaiDaTe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFaiDaTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumFaiDaTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextTempoSimulazione.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextTempoSimulazione.setText("7200");
        jTextTempoSimulazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTempoSimulazioneActionPerformed(evt);
            }
        });

        jTextNumeroProve.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextNumeroProve.setText("100");
        jTextNumeroProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroProveActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero Prove");

        jButtonAvvio.setText("Avvia Simulazione");
        jButtonAvvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextInterarrivo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextTempoSimulazione, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNumeroProve, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButtonAvvio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextInterarrivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumeroProve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTempoSimulazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAvvio, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextInterarrivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextInterarrivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextInterarrivoActionPerformed

    private void jTextOperatoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOperatoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOperatoreActionPerformed

    private void jTextNumOperatoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumOperatoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumOperatoreActionPerformed

    private void jTextFaiDaTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFaiDaTeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFaiDaTeActionPerformed

    private void jTextNumFaiDaTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumFaiDaTeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumFaiDaTeActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        boolean enabled = jCheckBox1.isSelected();
        jTextNumeroProve.setEditable(enabled);
        jLabel8.setEnabled(enabled);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextTempoSimulazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTempoSimulazioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTempoSimulazioneActionPerformed

    private void jTextNumeroProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroProveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroProveActionPerformed

    private void jButtonAvvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvvioActionPerformed
        try {
            double paramArrivi = Double.parseDouble(jTextInterarrivo.getText());
            double paramOperatore = Double.parseDouble(jTextOperatore.getText());
            int numOperatori = Integer.parseInt(jTextNumOperatore.getText());
            double paramFaiDaTe = Double.parseDouble(jTextFaiDaTe.getText());
            int numCasseFaiDaTe = Integer.parseInt(jTextNumFaiDaTe.getText());
            double tempoSimulazione = Double.parseDouble(jTextTempoSimulazione.getText());
            int numProveRipetute = Integer.parseInt(jTextNumeroProve.getText());
            
            
            verifica(numOperatori,numCasseFaiDaTe,paramArrivi,paramOperatore,
                    paramFaiDaTe,tempoSimulazione,numProveRipetute);
            
            if(jCheckBox1.isSelected()){
                
                Vector<Simulazione> listSimulazioni=new Vector<>();
                
                for (int j=0;j<numProveRipetute;j++){
                    Simulazione prova = new Simulazione(paramArrivi, numCasseFaiDaTe, numOperatori,
                        paramFaiDaTe, paramOperatore, tempoSimulazione);
                    listSimulazioni.insertElementAt(prova, j);
                }
                
                FrameProveRipetute simFrameRip=new FrameProveRipetute(listSimulazioni);
                simFrameRip.setLocationRelativeTo(null);
                simFrameRip.setVisible(true);
                this.setVisible(false);
                
            
            }
            
            else{
                Simulazione prova = new Simulazione(paramArrivi, numCasseFaiDaTe, numOperatori,
                        paramFaiDaTe, paramOperatore, tempoSimulazione);

                FrameSimulazione argFrame = new FrameSimulazione(prova);
                //new Thread(argFrame).start();
                argFrame.setLocationRelativeTo(null); // center to screen
                argFrame.setVisible(true);

                //prova.start();
                this.setVisible(false);
            }
        } catch(NumberFormatException | NullPointerException e){
	    JOptionPane.showMessageDialog(this, "Uno o più campi non correttamente inizializzati",
                    "Errore", JOptionPane.ERROR_MESSAGE);
	} catch(LimiteCasse | LimiteValori ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Errore", JOptionPane.ERROR_MESSAGE);
        }
          
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAvvioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvvio;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFaiDaTe;
    private javax.swing.JTextField jTextInterarrivo;
    private javax.swing.JTextField jTextNumFaiDaTe;
    private javax.swing.JTextField jTextNumOperatore;
    private javax.swing.JTextField jTextNumeroProve;
    private javax.swing.JTextField jTextOperatore;
    private javax.swing.JTextField jTextTempoSimulazione;
    // End of variables declaration//GEN-END:variables
}


class LimiteValori extends Exception{
    LimiteValori(){
        super("alcuni valori non sono corretti!!");
    }
}

class LimiteCasse extends Exception {

  LimiteCasse()
  {
    super("Il numero delle casse è compreso: \n"
            + "tra 0 e 11 - Fai Da Te\n"
            + "tra 0 e 23 - Operatore\n");
  }
}