/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simulazione;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author carlo
 */
public class PanelCassa extends javax.swing.JPanel {

    /**
     * Creates new form PanelCassa
     */
    Cassa cassaSelezionata;
    
    //immagine cliente
    BufferedImage img = null;
    
    public PanelCassa(Cassa cassaSelezionata) {

        
        this.cassaSelezionata=cassaSelezionata;

        initComponents();
        
        try {
            img = ImageIO.read(new File(getClass().getResource("/resources/cliente.png").getPath()));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        
        
        jScrollPane2.setViewportView(jPanel1);

        jLabel1.setEnabled(false);
        
    }

    
   
    
    void aggiornaPanel(){
        
        String str="";
        if(cassaSelezionata.getNumClienti()>0){
            jLabel1.setEnabled(true);
            str+=cassaSelezionata.idUtenteServito();
        }
        else{
            jLabel1.setEnabled(false);
        }
        
        
        jLabel2.setText("<html> numero clienti: "+cassaSelezionata.getNumClienti()+"<br>id utente servito: "+str+"</html>");
        repaint();   
        
        //il pannello viene modificato in jPanel1. guarda in design mode -> custom code
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            public void paint(Graphics g){

                for(int i=0;i<cassaSelezionata.getNumClienti();i++){
                    //g.setColor(new Color(i*50%255,i*100%255,i*150%255));
                    //g.fillRect(20, i*22, 20, 20);
                    g.drawImage(img, 20, i* (img.getHeight()+2) , this);
                    //g.drawString(String.valueOf(cassaSelezionata.idUtenteServito()), 0, i* (img.getHeight()+2));
                }

            }

        };
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(160, 393));
        setMinimumSize(new java.awt.Dimension(160, 393));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        switch(cassaSelezionata.getTipoCassa()){
            case FAIDATE:
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cassaOperatore1.jpg"))); // NOI18N
            break;
            case OPERATORE: jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cassaOperatore2.jpg"))); // NOI18N

            break;

        }

        jScrollPane2.setMaximumSize(new java.awt.Dimension(140, 215));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(140, 215));

        jPanel1.setMaximumSize(new java.awt.Dimension(138, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(138, 0));
        jPanel1.setLayout(null);
        jScrollPane2.setViewportView(jPanel1);

        jLabel2.setText("<html> numero clienti: <br>id utente servito: </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
